name: asim
channels:
  - conda-forge
  - defaults
dependencies:
  - backports
  - bleach
  - blosc
  - boto3
  - botocore
  - brotlipy
  - curl
  - decorator
  - entrypoints
  - flask
  - geopandas
  - hdf4
  - hdf5
  - ipykernel
  - ipython
  - ipython_genutils
  - itsdangerous
  - jedi
  - json-c
  - jsonschema
  - jupyter_client
  - jupyter_contrib_core
  - jupyter_core
  - krb5
  - mock
  - multidict
  - munch
  - nbclient
  - nbconvert
  - nbformat
  - notebook
  - numexpr
  - numpy
  - openjpeg
  - openssl
  - orca
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - patsy
  - pickleshare
  - pip
  - poppler
  - poppler-data
  - postgresql
  - prettytable
  - ptyprocess
  - pycparser
  - pygments
  - pytables
  - pytz
  - pyyaml
  - rtree
  - s3fs
  - s3transfer
  - scipy
  - send2trash
  - setuptools
  - shapely
  - six
  - sqlite
  - statsmodels
  - terminado
  - testpath
  - tiledb
  - tk
  - toolz
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - tzcode
  - tzdata
  - urbansim=3.2
  - urllib3
  - webencodings
  - wheel
  - wrapt
  - xerces-c
  - yaml
  - yarl
  - zeromq
  - zlib
  - zstd
  - pip:
    - idna
    - openmatrix
    - psutil
    - requests
    - zbox
