cbd_threshold: 2
chunk_size: 10000000000
distributed_vot_mu: 0.684
distributed_vot_sigma: 0.85
fail_fast: true
household_median_value_of_time:
  1: 6.01
  2: 8.81
  3: 10.44
  4: 12.86
households_sample_size: 20000
inherit_settings: true
input_table_list:
- column_map:
    cars: VEHICL
    household_id: household_id
    persons: hhsize
    workers: num_workers
  filename: households.csv
  index_col: household_id
  tablename: households
- column_map:
    member_id: PNUM
    person_id: person_id
  filename: persons.csv
  index_col: person_id
  tablename: persons
- column_map:
    COUNTY: county_id
    ZONE: TAZ
  filename: land_use.csv
  index_col: TAZ
  tablename: land_use
max_value_of_time: 50
mem_tick: 0
min_value_of_time: 1
models:
- initialize_landuse
- compute_accessibility
- initialize_households
- school_location
- workplace_location
- auto_ownership_simulate
- free_parking
- cdap_simulate
- mandatory_tour_frequency
- mandatory_tour_scheduling
- joint_tour_frequency
- joint_tour_composition
- joint_tour_participation
- joint_tour_destination
- joint_tour_scheduling
- non_mandatory_tour_frequency
- non_mandatory_tour_destination
- non_mandatory_tour_scheduling
- tour_mode_choice_simulate
- atwork_subtour_frequency
- atwork_subtour_destination
- atwork_subtour_scheduling
- atwork_subtour_mode_choice
- stop_frequency
- trip_purpose
- trip_destination
- trip_purpose_and_destination
- trip_scheduling
- trip_mode_choice
- generate_beam_plans
- write_data_dictionary
- write_tables
multiprocess: true
multiprocess_steps:
- begin: initialize_landuse
  name: mp_initialize
- begin: school_location
  name: mp_households
  slice:
    tables:
    - households
    - persons
- begin: generate_beam_plans
  name: mp_summarize
num_processes: 70
output_tables:
  action: include
  prefix: final_
  tables:
  - checkpoints
  - land_use
  - households
  - persons
  - tours
  - trips
  - joint_tour_participants
  - plans
rural_threshold: 6
skim_time_periods:
  labels:
  - EA
  - AM
  - MD
  - PM
  - EV
  period_minutes: 60
  periods:
  - 0
  - 6
  - 11
  - 16
  - 20
  - 24
skims_file: skims.omx
stagger: 0
strict: false
trace_hh_id: null
trace_od: null
urban_threshold: 4
use_shadow_pricing: false
