# read cached skims (using numpy memmap) from output directory (memmap is faster than omx )
read_skim_cache: True
# write memmapped cached skims to output directory after reading from omx, for use in subsequent runs
write_skim_cache: False

zone_system: 2
name: prototype_mtc

zone_system: 2

maz: maz.csv

maz_to_maz:
  tables:
    - maz_to_maz_walk.csv
    - maz_to_maz_bike.csv

  # maz_to_maz blending distance (missing or 0 means no blending)
  max_blend_distance:
    DIST: 5
    # blend distance of 0 means no blending
    DISTBIKE: 0
    DISTWALK: 1

  # missing means use the skim value itself rather than DIST skim (e.g. DISTBIKE)
  blend_distance_skim_name: DIST


taz_skims:
    omx: skims.omx
    zarr: skims.zarr
    zarr-digital-encoding:
        - regex: ".*_BOARDS"
          joint_dict: joined_board
        - regex: ".*_FAR"
          joint_dict: joined_fare
        - regex: ".*_XWAIT"
          joint_dict: joined_xwait
        - regex: ".*_WAUX"
          joint_dict: joined_waux
        - regex: ".*_IWAIT"
          joint_dict: joined_iwait
        - regex: ".*_KEYIVT"
          joint_dict: joined_keyivt
        - regex: ".*_WAIT"
          joint_dict: joined_wait
        - regex: "DISTWALK|DISTBIKE"
          joint_dict: joined_walkbike

skim_time_periods:
    time_window: 1440
    period_minutes: 60
    periods: [0, 3, 5, 9, 14, 18, 24] # 3=3:00-3:59, 5=5:00-5:59, 9=9:00-9:59, 14=2:00-2:59, 18=6:00-6:59
    labels: ['EA', 'EA', 'AM', 'MD', 'PM', 'EV']
