COEFFICIENTS: tour_mode_choice_coeffs.csv
COEFFICIENT_TEMPLATE: tour_mode_choice_coeffs_template.csv
CONSTANTS:
  TNC_shared_IVTFactor: 1.5
  TNC_shared_baseFare: 2.2
  TNC_shared_costMinimum: 3.0
  TNC_shared_costPerMile: 0.53
  TNC_shared_costPerMinute: 0.1
  TNC_shared_waitTime_mean:
    1: 5.0
    2: 8.0
    3: 11.0
    4: 15.0
    5: 15.0
  TNC_shared_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  TNC_single_baseFare: 2.2
  TNC_single_costMinimum: 7.2
  TNC_single_costPerMile: 1.33
  TNC_single_costPerMinute: 0.24
  TNC_single_waitTime_mean:
    1: 3.0
    2: 6.3
    3: 8.4
    4: 8.5
    5: 10.3
  TNC_single_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  Taxi_baseFare: 2.2
  Taxi_costPerMile: 2.3
  Taxi_costPerMinute: 0.1
  Taxi_waitTime_mean:
    1: 5.5
    2: 9.5
    3: 13.3
    4: 17.3
    5: 26.5
  Taxi_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  bikeSpeed: 12.0
  bikeThresh: 6.0
  biketimelong_multiplier: 20
  biketimeshort_multiplier: 4
  costPerMile: 18.29
  costShareSr2: 1.75
  costShareSr3: 2.5
  dacc_ratio: 0
  density_index_multiplier: -0.2
  drvtrn_distpen_0_multiplier: 270
  drvtrn_distpen_max: 15
  dtim_multiplier: 2
  indivTour: 1.0
  ivt_com_multiplier: 0.7
  ivt_cost_multiplier: 0.6
  ivt_exp_multiplier: 1
  ivt_ferry_multiplier: 0.8
  ivt_hvy_multiplier: 0.8
  ivt_lrt_multiplier: 0.9
  longWalk: 0.667
  long_i_wait_multiplier: 1
  maxCbdAreaTypeThresh: 2
  max_waitTime: 50
  min_waitTime: 0
  shortWalk: 0.333
  short_i_wait_multiplier: 2
  upperAM: 10
  upperEA: 5
  upperMD: 15
  upperPM: 19
  wacc_multiplier: 2
  waitThresh: 10.0
  walkSpeed: 3.0
  walkThresh: 1.5
  walktimelong_multiplier: 10
  walktimeshort_multiplier: 2
  waux_multiplier: 2
  wegr_multiplier: 2
  xfers_drv_multiplier: 20
  xfers_wlk_multiplier: 10
  xwait_multiplier: 2
LOGIT_TYPE: NL
LOGSUM_CHOOSER_COLUMNS:
- tour_type
- hhsize
- density_index
- age
- age_16_p
- age_16_to_19
- auto_ownership
- number_of_participants
- tour_category
- num_workers
- value_of_time
- free_parking_at_work
MODE_CHOICE_LOGSUM_COLUMN_NAME: mode_choice_logsum
NESTS:
  alternatives:
  - alternatives:
    - alternatives:
      - DRIVEALONEFREE
      - DRIVEALONEPAY
      coefficient: coef_nest_AUTO_DRIVEALONE
      name: DRIVEALONE
    - alternatives:
      - SHARED2FREE
      - SHARED2PAY
      coefficient: coef_nest_AUTO_SHAREDRIDE2
      name: SHAREDRIDE2
    - alternatives:
      - SHARED3FREE
      - SHARED3PAY
      coefficient: coef_nest_AUTO_SHAREDRIDE3
      name: SHAREDRIDE3
    coefficient: coef_nest_AUTO
    name: AUTO
  - alternatives:
    - WALK
    - BIKE
    coefficient: coef_nest_NONMOTORIZED
    name: NONMOTORIZED
  - alternatives:
    - alternatives:
      - WALK_LOC
      - WALK_LRF
      - WALK_EXP
      - WALK_HVY
      - WALK_COM
      coefficient: coef_nest_TRANSIT_WALKACCESS
      name: WALKACCESS
    - alternatives:
      - DRIVE_LOC
      - DRIVE_LRF
      - DRIVE_EXP
      - DRIVE_HVY
      - DRIVE_COM
      coefficient: coef_nest_TRANSIT_DRIVEACCESS
      name: DRIVEACCESS
    coefficient: coef_nest_TRANSIT
    name: TRANSIT
  - alternatives:
    - TAXI
    - TNC_SINGLE
    - TNC_SHARED
    coefficient: coef_nest_RIDEHAIL
    name: RIDEHAIL
  coefficient: coef_nest_root
  name: root
SPEC: tour_mode_choice.csv
nontour_preprocessor:
  DF: choosers
  SPEC: tour_mode_choice_annotate_choosers_preprocessor
  TABLES:
  - land_use
preprocessor:
  DF: choosers
  SPEC: tour_mode_choice_annotate_choosers_preprocessor
  TABLES:
  - land_use
  - tours
